version: '3'
services:
  microservice_user:
    container_name: 'microservice_user'
    volumes:
      - './microservices/user/:/usr/src/microservices/user'
      - '/usr/src/microservices/user/node_modules/'
    restart: always
    networks:
      - api_net
    build:
      context: ./microservices/user
      dockerfile: Dockerfile
  api:
    container_name: 'api'
    restart: always
    links:
      - microservice_user
    networks:
      - api_net
    volumes:
      - './api/:/usr/src/api'
      - '/usr/src/api/node_modules/'
    depends_on:
      - microservice_user
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

networks:
  api_net:
    driver: bridge
